{% set name = "molml" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/molml-{{ version }}.tar.gz
  sha256: 493b1a762fea3f3209ab78d1eb6ace39bb96c940b86d62c1b32e31c5a3862c0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pypandoc <1.8
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - bidict
    - future
    - pathos

test:
  imports:
    - molml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/crcollins/molml/
  summary: An interface between molecules and machine learning
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
